### ISSUE TITLE
How to install the sniffer firmware?

### ISSUE THREAD

**Issue by gstadler** [adafruit/Adafruit_BluefruitLE_Firmware#17]
I couldn't flash the 2 years old sniffer firmware with the iOS application or with the nRFGo studio. 

When I packaged it with nRFGo studio and tried to upload as bootloader it always said "Timeout waiting for acknowledgement from device. Failure to upgrade target. Error is: No data is received on serial port." I have tried different settings, rates and my device was in DFU mode.

With the ios application, at "custom firmware", I could not manage to get the init file right. I could not find the init file anywhere and using the .dat file created with nRFGo studo did not work because of some icloud issue. (Uploading the file is ok, but it is not selectable from the application). 

Regards,
Gellért

**Comment by ladyada** [comment]
you must use a jlink - you cannot use the bootloader

**Comment by jrddunbr** [comment]
@ladyada The [tutorial on the Adafruit website](https://learn.adafruit.com/introducing-adafruit-ble-bluetooth-low-energy-friend/ble-sniffer) has hardly information on how to deploy the sniffer software with _any_ method, and if we need to be able to use a Segger J-Link to do that, I would really appreciate instructions.

I literally bought the device just to run this software, to debug some Bluetooth connections for another project.

Can we get an updated tutorial? It's also my understanding that the installation process for the software on the computer has also changed from using an EXE file to a new method directly with Wireshark.

Much appreciated :)

**Comment by ladyada** [comment]
if you purchased the BLE sniffer from the adafruit site it comes pre-installed with the bluetooth sniffer firmware

questions about how to use adafruit products are best posted in the adafruit forums  at [forums.adafruit.com](forums.adafruit.com/)
thats where tech support is handled - github issues are where folks can issue bug reports (e.g. something that ought to work but doesnt due to a hardware or software bug)

thanks! :)
