### ISSUE TITLE
ANCS and firmware source release

### ISSUE THREAD

**Issue by SolidHal** [adafruit/Adafruit_BluefruitLE_Firmware#19]
On the product page FAQ, it says ANCS should be expected sometime during version 0.7. I was wondering if there are any updates regarding to ANCS support in the near future? 

Related, in another issue that has since been closed it is mentioned that the source code for the firmware would be made open eventually, however that was nearly two years ago. I'd be happy to contribute to adding ANCS support if it were made open source, and I imagine many other devs would like to help as well. 

Thanks -SH

**Comment by microbuilder** [comment]
We have tried to resolve the license issues with Nordic, but are unable to open source the SW because we couldn't get the license changed on the files we are using. I would suggest looking at the nRF52 family where all of the source is available (newer SDK and license terms), and where all current development is happening, including ANCS support. There is already an ANCS demo here, for example: https://github.com/adafruit/Adafruit_nRF52_Arduino/blob/master/libraries/Bluefruit52Lib/examples/Peripheral/ancs/ancs.ino

**Comment by SolidHal** [comment]
What version of the SDK does the adafruit nRF51 firmware use?
Is there any reason the precompiled examples in SDK 12 or 8 provided by nordic wouldn't function properly on the uart blefrient32?
