### ISSUE TITLE
Unable to program Bluefruit LE Friend V1 as sniffer

### ISSUE THREAD

**Issue by fabiencomte** [adafruit/Adafruit_BluefruitLE_Firmware#3]
Please say the files and the order to use. Board is not responding after using sniffer firmware.

If I want to program as normal (5.0) it's broken too. What is the right order ?

**Comment by microbuilder** [comment]
As mentioned in the FAQ (https://learn.adafruit.com/introducing-adafruit-ble-bluetooth-low-energy-friend/faq#faq-7) we don't support reflashing boards across versions, which is why we offer two completely separate products (the sniffer and the Bluefruit LE Friend). The HW is the same, but changing isn't without risk and requires external HW like a Segger J-Link to perform.

The normal boards use a special bootloader with fail safe over the air (OTA) updates, and the sniffer is a single completely independant image with no bootloader and no soft-device image, so once you erase the contents of flash on the Bluefruit LE Friend we have absolutely no way to get you 'back' to a known good state without extra external HW, and can't really offer any support for that.

Have a look at the FAQ linked about which references the tools we use internally to flash boards, and the AdaLink readme describes everything you need to know to reflash a board using a Seger J-Link.  An STLink/V2 should work as well, though from experience the J-Link is more reliable if you have access to one.

Also, please post support questions on the Adafruit Support Forums (under Wireless).  The support team doesn't receive any of these email alerts from Github, so you're less likely to get an answer from the right people.

**Comment by microbuilder** [comment]
PS: If you have only tried to flash the sniffer firmware using the OTA firmware tool (which won't work!), the bootloader on your Bluefruit LE Friend should still be intact, and you can enter DFU mode by holding down the DFU button when you insert your board, which should cause the LED to flash at a constant rate.  Please post the results of this up as a new thread in the Adafruit support forum under wireless, though.

**Comment by fabiencomte** [comment]
Hello,
I found a sequence that works for my BLEFRIEND V1 with nrfgo,
Erase allProgram application (sniffer)Program soft device (v0.7)Program bootloader (v0000)
Thank you for your help.
     De : Kevin Townsend <notifications@github.com>
 À : adafruit/Adafruit_BluefruitLE_Firmware <Adafruit_BluefruitLE_Firmware@noreply.github.com> 
Cc : Fabien COMTE <comte_fabien@yahoo.fr> 
 Envoyé le : Mercredi 2 septembre 2015 18h39
 Objet : Re: [Adafruit_BluefruitLE_Firmware] Unable to program Bluefruit LE Friend V1 as sniffer (#3)
   
As mentioned in the FAQ (https://learn.adafruit.com/introducing-adafruit-ble-bluetooth-low-energy-friend/faq#faq-7) we don't support reflashing boards across versions, which is why we offer two completely separate products (the sniffer and the Bluefruit LE Friend). The HW is the same, but changing isn't without risk and requires external HW like a Segger J-Link to perform.The normal boards use a special bootloader with fail safe over the air (OTA) updates, and the sniffer is a single completely independant image with no bootloader and no soft-device image, so once you erase the contents of flash on the Bluefruit LE Friend we have absolutely no way to get you 'back' to a known good state without extra external HW, and can't really offer any support for that.Have a look at the FAQ linked about which references the tools we use internally to flash boards, and the AdaLink readme describes everything you need to know to reflash a board using a Seger J-Link. An STLink/V2 should work as well, though from experience the J-Link is more reliable if you have access to one.Also, please post support questions on the Adafruit Support Forums (under Wireless). The support team doesn't receive any of these email alerts from Github, so you're less likely to get an answer from the right people.—
